import "./globals.css";
import { Fira_Mono } from "next/font/google";

const firaMono = Fira_Mono({
  weight: "700",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={firaMono.className}>
        <main>{children}</main>
      </body>
    </html>
  );
}
